[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
kinlend_protocol = "5NYiLMkYrumBZnnjUeDQfjod1agKCCeYzFpHqCZcCjzt"

[registry]
url = "http://127.0.0.1:8899"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/dev.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 100000000 tests/**/*.ts"
