[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
kinlend_protocol = "5NYiLMkYrumBZnnjUeDQfjod1agKCCeYzFpHqCZcCjzt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/dev.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
